assets:
  settings.xml: kerelape/reikai-secrets#settings.xml
install: |
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Plint --errors -Dstyle.color=never
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Plint -Dinvoker.skip
    mvn clean deploy --errors --settings ../settings.xml -Dstyle.color=never